name: Publish NPM

on:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: |
            r1/${{ runner.os }}/npm/${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            r1/${{ runner.os }}/npm/

      - name: Clean git working directory
        run: |
          git reset --hard || echo "No changes to reset"
          git clean -fd || echo "No files to clean"

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump version
        id: bump_version
        run: |
          # Uncomment the desired version bump type
          npm version patch --no-git-tag-version
          # npm version minor
          # npm version major
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
      - name: Commit and push changes
        run: |
          git add package.json package-lock.json README.md
          git commit -m "Bump version to $NEW_VERSION"
          git tag "v$NEW_VERSION"
          git push origin publish --tags

      - name: Configure npm for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Check if version exists in GitHub Packages
        id: check_version_github
        run: |
          EXISTING_VERSION=$(npm view @jenesei-software/jenesei-ui-react versions --registry https://npm.pkg.github.com --json | grep ${NEW_VERSION} || true)
          if [ -n "$EXISTING_VERSION" ]; then
            echo "Version ${NEW_VERSION} already exists. Skipping publish."
            echo "publishGH=false" >> $GITHUB_ENV
          else
            echo "publishGH=true" >> $GITHUB_ENV
          fi

      - name: Configure npm for NPM Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_CYRILSTRONE_TOKEN }}" >> ~/.npmrc

      - name: Check if version exists in NPM
        id: check_version_npm
        run: |
          EXISTING_VERSION=$(npm view @jenesei-software/jenesei-plugin-vite versions --json | grep ${NEW_VERSION} || true)
          if [ -n "$EXISTING_VERSION" ]; then
            echo "Version ${NEW_VERSION} already exists. Skipping publish."
            echo "publishNPM=false" >> $GITHUB_ENV
          else
            echo "publishNPM=true" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        if: env.publishGH == 'true' && env.publishNPM == 'true'
        run: |
          npm ci

      - name: Build
        if: env.publishGH == 'true' && env.publishNPM == 'true'
        run: |
          npm run build

      - name: Publish to GitHub Packages
        if: env.publishGH == 'true' && env.publishNPM == 'true'
        run: |
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        if: env.publishGH == 'true' && env.publishNPM == 'true'
        run: |
          npm publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CYRILSTRONE_TOKEN }}
